config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'archive/index'
  resources :entres
  root to: "entres#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entre.rb
class Entre < ApplicationRecord
    validates :calories, :protiens , :carbohydrates, :fats, :meal_type, presence: true


    def day
    self.created_at.strftime("%b %e, %Y")
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archive_controller.rb
class ArchiveController < ApplicationController
  def index
    @entres = Entre.all.group_by(&:day)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title)
    end
end

app/controllers/entres_controller.rb
class EntresController < ApplicationController
  before_action :set_entre, only: %i[ show edit update destroy ]

  # GET /entres or /entres.json
  def index
    @entres = Entre.where("created_at >=?", Date.today)
  end

  # GET /entres/1 or /entres/1.json
  def show
  end

  # GET /entres/new
  def new
    @entre = Entre.new
  end

  # GET /entres/1/edit
  def edit
  end

  # POST /entres or /entres.json
  def create
    @entre = Entre.new(entre_params)

    respond_to do |format|
      if @entre.save
        format.html { redirect_to entre_url(@entre), notice: "Entre was successfully created." }
        format.json { render :show, status: :created, location: @entre }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entres/1 or /entres/1.json
  def update
    respond_to do |format|
      if @entre.update(entre_params)
        format.html { redirect_to entre_url(@entre), notice: "Entre was successfully updated." }
        format.json { render :show, status: :ok, location: @entre }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entres/1 or /entres/1.json
  def destroy
    @entre.destroy

    respond_to do |format|
      format.html { redirect_to entres_url, notice: "Entre was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entre
      @entre = Entre.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entre_params
      params.require(:entre).permit(:meal_type, :calories, :protiens, :carbohydrates, :fats)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archive_helper.rb
module ArchiveHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/entres_helper.rb
module EntresHelper
end

app/views/archive/index.html.erb
<div class="columns is-centered">
<div class="column is-half">
<%= @entres.each do |day , entres|%>
<h3 class="is-size-4 has-text-weight-bold mb-4">entries for <%= day %></h3>

<nav class="level is-mobile">
<div class="level-item has-text-center">
<div>
<p class="heading">calories</p>
<p class="title"><%= entres.pluck(:calories).sum %></p>

</div>
</div>

<div class="level-item has-text-center">
<div>
<p class="heading">protiens</p>
<p class="title"><%= entres.pluck(:protiens).sum %>g</p>

</div>
</div>

<div class="level-item has-text-center">
<div>
<p class="heading">carbohydrates</p>
<p class="title"><%= entres.pluck(:carbohydrates).sum %>g</p>

</div>
</div>

<div class="level-item has-text-center">
<div>
<p class="heading">fats</p>
<p class="title"><%= entres.pluck(:fats).sum %>g</p>

</div>
</div>
</nav>

<% entres.each do |entre|%>
<%= link_to entre_path(entre) do%>
<div class="card">
<div class="card-content">
<strong><%= entre.meal_type%></strong><br/>
<%= entre.calories%>calories
<%= entre.protiens%>protiens
<%= entre.carbohydrates%>carbohydrates
<%= entre.fats%>fats
</div>
</div>
<%end%>
<%end%>
<%end%>
</div>
</div>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Title:</strong>
    <%= category.title %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/entres/_entre.html.erb
<div id="<%= dom_id entre %>">
  <p>
    <strong>Meal type:</strong>
    <%= entre.meal_type %>
  </p>

  <p>
    <strong>Calories:</strong>
    <%= entre.calories %>
  </p>

  <p>
    <strong>Protiens:</strong>
    <%= entre.protiens %>
  </p>

  <p>
    <strong>Carbohydrates:</strong>
    <%= entre.carbohydrates %>
  </p>

  <p>
    <strong>Fats:</strong>
    <%= entre.fats %>
  </p>

</div>

app/views/entres/_form.html.erb
<%= form_with(model: entre) do |form| %>
  <% if entre.errors.any? %>
    <div class="message is-danger">
    <div class="message-header">
      <p><%= pluralize(entre.errors.count, "error") %> prohibited this entre from being saved:</p>
    </div>

<div class="message-body">
      <ul>
        <% entre.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %> 
      </ul>
    </div>
    </div>
  <% end %>

  <div>
    <%= form.label :meal_type, style: "display: block", class: "label" %>
    <%= form.text_field :meal_type, class:"input" %>
  </div>

  <div>
    <%= form.label :calories, style: "display: block", class: "label" %>
    <%= form.number_field :calories , class:"input"%>
  </div>

  <div>
    <%= form.label :protiens, style: "display: block", class: "label" %>
    <%= form.number_field :protiens, class:"input" %>
  </div>

  <div>
    <%= form.label :carbohydrates, style: "display: block",  class: "label"%>
    <%= form.number_field :carbohydrates, class:"input" %>
  </div>

  <div>
    <%= form.label :fats, style: "display: block",  class: "label"%>
    <%= form.number_field :fats, class:"input" %>
  </div>
<br>
  <div>
    <%= form.submit class:"button is-success" %>
  </div>
<% end %>

app/views/entres/edit.html.erb
<div class="columns is-centered mt-6">
<div class="column is-one-third">
<h1 class="is-size-2 has-text-weight-bold mb-3">Editing entre</h1>

<%= render "form", entre: @entre %>



</div>

</div>

app/views/entres/index.html.erb
<div class="columns is-centered mt-6">
  <% @entres.each do |entre| %>
  <div class="column is-one-quarter">
  <div class="card">
  <header class="card-header">
  <p class="card-header-title">
  <%= entre.meal_type%>
  </p>
  </header>

  <div class="card-content">
  <div class="content">
    <p><span class="has-text-weight-bold"><%= entre.calories%></span> calories</p>
    <p><span class="has-text-weight-bold"><%= entre.protiens%></span> protiens</p>
    <p><span class="has-text-weight-bold"><%= entre.carbohydrates%></span> grams of carbohydrates</p>
    <p><span class="has-text-weight-bold"><%= entre.fats%></span> grams of fats</p>
    <p class="italic">Logged <%= time_ago_in_words(entre.created_at)%> ago</p>
  </div>
  </div>
  <div class="card-footer">
    <p><%= link_to "Show", entre, class: "card-footer-item" %></p>
    <p><%= link_to "Edit", edit_entre_path(entre), class: "card-footer-item" %></p>
    <p><%= link_to "Destroy", entre, method: :delete, data:{ confirm:'are you sure? '}, class: "card-footer-item" %></p>
  </div>
  </div>
  </div>
  <% end %>
</div>

<div class="columns is-centered mt-6">
<%= link_to "View all entries", archive_index_path, class: "button is-link is-outlined is-centered"%>
</div>

app/views/entres/new.html.erb
<div class="columns is-centered mt-6">
<div class="column is-one-third">
<h1 class="is-size-2 has-text-weight-bold mb-3">new entre</h1>

<%= render "form", entre: @entre %>



</div>

</div>

app/views/entres/show.html.erb
<%= content_for :title do %>
<%= @entre.meal_type%> &ndash; <%= DateTime.now %>
<%end%>


<div class="columns is-centered mt-6">
<div class="column is-one-third">
<nav class="panel is-link">

<p class="panel-heading">
meal_type: 
<%= @entre.meal_type%>
</p>

<div class="panel-block">
calories: <%= @entre.calories%>
</div>

<div class="panel-block">
protiens: <%= @entre.protiens%>
</div>
<div class="panel-block">
carbohydrates: <%= @entre.carbohydrates%>
</div>
<div class="panel-block">
fats: <%= @entre.fats%>
</div>
</nav>

<div class="columns is-mobile">
  <%= link_to "Edit", edit_entre_path(@entre), class: "button is-gray" %> |
  <%= link_to "Delete", entre_path(@entre), method: :delete, data: {confirm: 'Are you Sure'}, class:"button is-gray" %>
</div>
<div class="column"></div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <%= render "shared/header"%>
  <%if notice.present?%>
  <div class="notification is-link is-light"><%= notice %></div>
<%end%>

  <%if alert.present?%>
  <div class="notification is-danger is-light"><%= alert %></div>
<%end%>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
  <%= link_to root_path, class: "navbar-item" do%>
  <span class="has-text-weight-bold is-size-4 ml-4">Foodlog</span>
  <%end%>



    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
    <span class="navbar-item">
     <%= link_to "Create new Entre", new_entre_path, class: "button is-success"  %>
    </span>
     
        </div>
      </div>
    </div>


  </div>
</nav>